// spiral_kernel_test_int4.cpp
// =======================
//
// Standalone tester for SPIRAL_INT4 mul_mat kernel (CUDA / Metal portable).
//
// Loads fixtures generated by spiral_test_gen_int4.py, calls the kernel via
// ggml's backend (CUDA on Linux, Metal on Mac), writes output for verification
// by Python.
//
// Build (from spiral root):
//   cmake --build build --target spiral_kernel_test_int4
//
// Run:
//   python spiral_test_gen_int4.py --m 2048 --k 2048 --n 1 --out fixture_int4/
//   ./build/bin/spiral_kernel_test_int4 fixture_int4/
//   python verify_spiral_kernel.py fixture_int4/

#include "ggml.h"
#include "ggml-alloc.h"
#include "ggml-backend.h"
#include "ggml-cpu.h"

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

// ── Read entire file into a vector ─────────────────────────────────────
static std::vector<uint8_t> read_file(const std::string & path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) {
        fprintf(stderr, "ERROR: cannot open %s\n", path.c_str());
        exit(1);
    }
    size_t sz = f.tellg();
    f.seekg(0);
    std::vector<uint8_t> buf(sz);
    f.read((char *)buf.data(), sz);
    return buf;
}

// ── Read a key=value style integer from meta.json (poor man's JSON) ────
static int64_t read_meta_int(const std::string & meta_path, const std::string & key) {
    std::ifstream f(meta_path);
    std::string line;
    std::string needle = "\"" + key + "\":";
    while (std::getline(f, line)) {
        size_t p = line.find(needle);
        if (p == std::string::npos) continue;
        // find the digit after the colon
        p = line.find_first_of("0123456789-", p + needle.size());
        if (p == std::string::npos) continue;
        size_t e = line.find_first_not_of("0123456789-", p);
        std::string num = line.substr(p, e - p);
        return std::stoll(num);
    }
    fprintf(stderr, "ERROR: key '%s' not found in %s\n", key.c_str(), meta_path.c_str());
    exit(1);
}

int main(int argc, char ** argv) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <fixture_dir>\n", argv[0]);
        return 1;
    }
    std::string fixture_dir = argv[1];

    // ── 1. Read meta.json ──────────────────────────────────────────────
    std::string meta_path = fixture_dir + "/meta.json";
    int64_t m = read_meta_int(meta_path, "m");
    int64_t k = read_meta_int(meta_path, "k");
    int64_t n = read_meta_int(meta_path, "n");
    int64_t weight_blob_bytes = read_meta_int(meta_path, "weight_blob_bytes");
    int64_t x_rotated_bytes = read_meta_int(meta_path, "x_rotated_bytes");
    int64_t y_reference_bytes = read_meta_int(meta_path, "y_reference_bytes");

    fprintf(stderr, "Fixture: m=%lld k=%lld n=%lld\n",
            (long long)m, (long long)k, (long long)n);

    // ── 2. Read fixture binary files ───────────────────────────────────
    auto x_rotated_bytes_buf = read_file(fixture_dir + "/x_rotated.bin");
    auto weight_blob_buf = read_file(fixture_dir + "/weight_packed.bin");

    if ((int64_t)x_rotated_bytes_buf.size() != x_rotated_bytes) {
        fprintf(stderr, "x_rotated size mismatch: got %zu, expected %lld\n",
                x_rotated_bytes_buf.size(), (long long)x_rotated_bytes);
        return 1;
    }
    if ((int64_t)weight_blob_buf.size() != weight_blob_bytes) {
        fprintf(stderr, "weight size mismatch: got %zu, expected %lld\n",
                weight_blob_buf.size(), (long long)weight_blob_bytes);
        return 1;
    }

    fprintf(stderr, "Read fixtures: x_rotated=%zu bytes, weight=%zu bytes\n",
            x_rotated_bytes_buf.size(), weight_blob_buf.size());

    // ── 3. Initialize a GPU backend (CUDA on Linux, Metal on Mac) ──────
    ggml_backend_dev_t dev = ggml_backend_dev_by_type(GGML_BACKEND_DEVICE_TYPE_GPU);
    if (!dev) {
        fprintf(stderr, "ERROR: no GPU backend device available\n");
        return 1;
    }
    ggml_backend_t backend = ggml_backend_dev_init(dev, nullptr);
    if (!backend) {
        fprintf(stderr, "ERROR: failed to initialize GPU backend\n");
        return 1;
    }
    fprintf(stderr, "GPU backend initialized: %s\n", ggml_backend_dev_name(dev));

    // ── 4. Build ggml context with both tensors ────────────────────────
    // We need:
    //   weight: SPIRAL_INT4, shape [k, m]   (ggml convention: cols are k, rows are m)
    //   input:  F32,         shape [k, n]
    //   output: F32,         shape [m, n]   (= weight @ input)
    //
    // ggml mul_mat does: output[i,j] = sum_k(weight[k,i] * input[k,j])
    // which matches: y_python = x @ W.T  (with x:[n,k], W:[m,k], y:[n,m])
    // since each col of input is a token, each col of output is the matmul result.

    struct ggml_init_params iparams = {
        /* .mem_size   = */ 1024 * 1024 * 1024,  // 1 GB scratch
        /* .mem_buffer = */ NULL,
        /* .no_alloc   = */ true,  // we use the backend allocator
    };
    struct ggml_context * ctx = ggml_init(iparams);

    struct ggml_tensor * w = ggml_new_tensor_2d(ctx, GGML_TYPE_SPIRAL_INT4, k, m);
    struct ggml_tensor * x = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, k, n);
    ggml_set_name(w, "w");
    ggml_set_name(x, "x");

    // mul_mat: output [m, n] = w [k, m] * x [k, n]
    struct ggml_tensor * y = ggml_mul_mat(ctx, w, x);
    ggml_set_name(y, "y");

    // ── 5. Allocate buffers on the backend ─────────────────────────────
    ggml_backend_buffer_t buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
    if (!buf) {
        fprintf(stderr, "ERROR: failed to allocate backend buffers\n");
        return 1;
    }

    // ── 6. Upload weight and input data ────────────────────────────────
    // Verify size matches what we expect
    size_t w_expected = ggml_nbytes(w);
    if ((int64_t)w_expected != weight_blob_bytes) {
        fprintf(stderr, "WARNING: ggml says weight is %zu bytes, fixture is %lld bytes\n",
                w_expected, (long long)weight_blob_bytes);
        fprintf(stderr, "         (Continuing — may be padding/alignment difference.)\n");
    }
    size_t x_expected = ggml_nbytes(x);
    if ((int64_t)x_expected != x_rotated_bytes) {
        fprintf(stderr, "WARNING: ggml says x is %zu bytes, fixture is %lld bytes\n",
                x_expected, (long long)x_rotated_bytes);
    }

    ggml_backend_tensor_set(w, weight_blob_buf.data(),
                            0, std::min(w_expected, weight_blob_buf.size()));
    ggml_backend_tensor_set(x, x_rotated_bytes_buf.data(),
                            0, std::min(x_expected, x_rotated_bytes_buf.size()));

    fprintf(stderr, "Uploaded weight (%zu bytes) and input (%zu bytes)\n",
            w_expected, x_expected);

    // ── 7. Build computation graph and run ─────────────────────────────
    struct ggml_cgraph * gf = ggml_new_graph(ctx);
    ggml_build_forward_expand(gf, y);

    enum ggml_status status = ggml_backend_graph_compute(backend, gf);
    if (status != GGML_STATUS_SUCCESS) {
        fprintf(stderr, "ERROR: graph compute failed (status=%d)\n", (int)status);
        return 1;
    }
    fprintf(stderr, "Graph computed successfully\n");

    // ── 8. Read back output ────────────────────────────────────────────
    size_t y_bytes = ggml_nbytes(y);
    if ((int64_t)y_bytes != y_reference_bytes) {
        fprintf(stderr, "WARNING: y output is %zu bytes, expected %lld bytes\n",
                y_bytes, (long long)y_reference_bytes);
    }

    std::vector<uint8_t> y_data(y_bytes);
    ggml_backend_tensor_get(y, y_data.data(), 0, y_bytes);

    // ── 9. Write output file ───────────────────────────────────────────
    std::string out_path = fixture_dir + "/y_kernel.bin";
    std::ofstream out(out_path, std::ios::binary);
    out.write((const char *)y_data.data(), y_data.size());
    out.close();

    fprintf(stderr, "Wrote %s (%zu bytes)\n", out_path.c_str(), y_data.size());

    // ── 10. Cleanup ────────────────────────────────────────────────────
    ggml_backend_buffer_free(buf);
    ggml_free(ctx);
    ggml_backend_free(backend);

    return 0;
}
