#!/usr/bin/env python
"""
verify_spiral_kernel.py
========================

Compare standalone kernel output (y_kernel.bin) against Python ground truth
(y_reference.bin) generated by spiral_test_gen.py.

Usage:
  python verify_spiral_kernel.py fixture/

Reports:
  - Per-token (row of output) relative error
  - Per-output-position chunked statistics (to detect localized breakage)
  - Overall PASS/FAIL with thresholds
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

import numpy as np


def main():
    p = argparse.ArgumentParser()
    p.add_argument('fixture_dir', type=Path)
    p.add_argument('--quant-tolerance', type=float, default=0.05,
                   help='allowed kernel-vs-postquant-reference relative error '
                        '(reference is already quantized, so error should be tiny)')
    args = p.parse_args()

    d = args.fixture_dir
    meta = json.loads((d / "meta.json").read_text())
    m, k, n = meta['m'], meta['k'], meta['n']

    y_ref_path = d / "y_reference.bin"
    y_kernel_path = d / "y_kernel.bin"

    if not y_kernel_path.exists():
        print(f"ERROR: {y_kernel_path} doesn't exist. Run the C++ standalone tester first.")
        return 1

    y_ref = np.frombuffer(y_ref_path.read_bytes(), dtype=np.float32).reshape(n, m)
    y_kernel = np.frombuffer(y_kernel_path.read_bytes(), dtype=np.float32).reshape(n, m)

    print(f"Shapes: y_ref={y_ref.shape}, y_kernel={y_kernel.shape}")
    print(f"y_reference: norm={np.linalg.norm(y_ref):.4f}, range=[{y_ref.min():.4f}, {y_ref.max():.4f}]")
    print(f"y_kernel:    norm={np.linalg.norm(y_kernel):.4f}, range=[{y_kernel.min():.4f}, {y_kernel.max():.4f}]")
    print()

    if not np.all(np.isfinite(y_kernel)):
        n_nan = np.isnan(y_kernel).sum()
        n_inf = np.isinf(y_kernel).sum()
        print(f"FAIL: y_kernel contains {n_nan} NaN and {n_inf} Inf values")
        return 1

    # Overall error
    diff = y_kernel - y_ref
    overall_rel_err = np.linalg.norm(diff) / (np.linalg.norm(y_ref) + 1e-12)
    print(f"Overall relative error: {overall_rel_err:.4f}")
    print(f"  (Lloyd-Max 3-bit baseline is ~0.19; threshold = {args.quant_tolerance})")
    print()

    # Per-token (per-row of n) errors
    print("Per-token relative errors:")
    print(f"  {'tok':>4} | {'||py||':>10} | {'||kr||':>10} | {'rel_err':>8}")
    for t in range(n):
        py_t = y_ref[t]
        kr_t = y_kernel[t]
        rel = np.linalg.norm(kr_t - py_t) / (np.linalg.norm(py_t) + 1e-12)
        marker = "  ✗" if rel > args.quant_tolerance else "  ✓"
        print(f"  {t:>4} | {np.linalg.norm(py_t):>10.4f} | {np.linalg.norm(kr_t):>10.4f} | {rel:>8.4f}{marker}")
    print()

    # Output-position chunked statistics
    chunk_size = max(m // 8, 128)
    print(f"Output-position chunked stats (chunks of {chunk_size}):")
    print(f"  {'range':>14} | {'py.mean':>10} | {'py.std':>10} | {'kr.mean':>10} | {'kr.std':>10} | {'chunk_rel':>10}")
    n_bad_chunks = 0
    for start in range(0, m, chunk_size):
        end = min(start + chunk_size, m)
        py_chunk = y_ref[:, start:end]
        kr_chunk = y_kernel[:, start:end]
        chunk_rel = np.linalg.norm(kr_chunk - py_chunk) / (np.linalg.norm(py_chunk) + 1e-12)
        bad = chunk_rel > args.quant_tolerance
        if bad: n_bad_chunks += 1
        marker = "  ✗" if bad else ""
        print(f"  [{start:>5},{end:>5}) | {py_chunk.mean():>+10.5f} | {py_chunk.std():>10.5f} | "
              f"{kr_chunk.mean():>+10.5f} | {kr_chunk.std():>10.5f} | {chunk_rel:>10.4f}{marker}")
    print()

    # Verdict
    print("=" * 60)
    if overall_rel_err > args.quant_tolerance:
        print(f"FAIL: overall rel_err = {overall_rel_err:.4f} > {args.quant_tolerance}")
        print(f"      Reference is the POST-QUANT decoded weight, so any non-trivial")
        print(f"      error means the kernel computes something different than CPU dequant.")
        if n_bad_chunks > 0:
            print(f"      {n_bad_chunks} output chunks broken; pattern visible above.")
        return 1
    else:
        print(f"PASS: rel_err = {overall_rel_err:.4f}")
        print(f"      Kernel matches Python-decoded reference within tolerance.")
        return 0


if __name__ == "__main__":
    sys.exit(main())
